### ISSUE TITLE
500 server error when changing password

### ISSUE THREAD

**Issue by the21st** [jupyterhub/firstuseauthenticator#24]
When visiting `<server>/hub/auth/change-password` and trying to set a new password, I get a 500 server error.

I followed the DigitalOcean setup guide for tljh.

Here are the logs:

```
[E 2019-08-27 08:42:25.212 JupyterHub web:1788] Uncaught exception POST /hub/auth/change-password
    HTTPServerRequest(protocol='http', host='<ip>', method='POST', uri='/hub/auth/change
    Traceback (most recent call last):
      File "/opt/tljh/hub/lib/python3.6/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/tljh/hub/lib/python3.6/site-packages/firstuseauthenticator/firstuseauthenticator.
        self.authenticator.reset_password(user.name, new_password)
    AttributeError: 'coroutine' object has no attribute 'name'
Aug 27 08:42:25 jupyterhub python3[10019]:
[E 2019-08-27 08:42:25.230 JupyterHub log:166] {
      "Host": "<ip>",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, li
      "Content-Length": "30",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q
      "Accept-Encoding": "gzip, deflate",
      "Accept-Language": "en-GB,en;q=0.9,en-US;q=0.8,sk;q=0.7,cs;q=0.6",
      "Cache-Control": "max-age=0",
      "Content-Type": "application/x-www-form-urlencoded",
      "Cookie": "jupyterhub-hub-login=[secret]; jupyterhub-session-id=[secret]; _xsrf=[secret]",
      "Dnt": "1",
      "Origin": "http://<ip>",
      "Referer": "http://<ip>/hub/auth/change-password",
      "Upgrade-Insecure-Requests": "1",
      "X-Forwarded-For": "<ip>",
      "X-Forwarded-Host": "<ip>",
      "X-Forwarded-Port": "80",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Server": "jupyterhub",
      "X-Real-Ip": "<ip>"
    }
[E 2019-08-27 08:42:25.231 JupyterHub log:174] 500 POST /hub/auth/change-password (admin@<ip>) 28.16ms
```

**Comment by GeorgianaElena** [comment]
Hi @the21st! Thanks for reporting this issue. I believe this should be already solved by https://github.com/jupyterhub/firstuseauthenticator/pull/23.

**Comment by consideRatio** [comment]
I'll go ahead and close this issue, please report back if it isn't solved. There needs to be a release for #23 to be available simply with PyPI though.
